name: Nightly Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # run at 7 AM UTC (2am central)


env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2
  TZ: ":America/Chicago"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
      - run: npm ci
      - run: sed -i.bak "s/<p id=\"date\">.*<\/p>/<p id=\"date\">$(date -u)<\/p>/" src/components/ExploreContainer.tsx && rm src/components/*.bak
      - run: npm run build
      - run: npx muletrain deploy --id "$(date +%Y%m%d)" --channel nightly
      
