name: Deploy Release

on:
  release: 
    types: [ published ]

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2
  REGEX: "[0-9]+\\.[[0-9]+\\.[0-9]+\\-([^\\.]+)"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.0.0
      - name: Get the version
        id: get_version
        run: echo '::set-output name=VERSION::${GITHUB_REF/refs\/tags\/}'
      - name: Get the channel from semver
        id: get_channel
        run: echo '::set-output name=CHANNEL::$(if [[ "${{ steps.get_version.outputs.VERSION }}" =~ $REGEX ]]; then echo "${BASH_REMATCH[1]}"; else echo "production"; fi)'
      - run: npm ci
      - run: npm run build
      - run: npx muletrain deploy --id "${{ steps.get_version.outputs.VERSION }}" --channel "${{ steps.get_channel.outputs.CHANNEL }}"
      
